// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    appId: '1:322888842794:web:9b51e47da1c95fb280cd53',
    messagingSenderId: '322888842794',
    projectId: 'gesturo-a6e9c',
    authDomain: 'gesturo-a6e9c.firebaseapp.com',
    storageBucket: 'gesturo-a6e9c.firebasestorage.app',
    measurementId: 'G-KB0DKQ48G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    appId: '1:322888842794:android:9622fb3e75ab151a80cd53',
    messagingSenderId: '322888842794',
    projectId: 'gesturo-a6e9c',
    storageBucket: 'gesturo-a6e9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    appId: '1:322888842794:ios:4f0db9db0b27919a80cd53',
    messagingSenderId: '322888842794',
    projectId: 'gesturo-a6e9c',
    storageBucket: 'gesturo-a6e9c.firebasestorage.app',
    iosBundleId: 'com.example.gesturo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSn56LrSCbtSVnkFMgypCnde8p4dJ5zIo',
    appId: '1:322888842794:ios:4f0db9db0b27919a80cd53',
    messagingSenderId: '322888842794',
    projectId: 'gesturo-a6e9c',
    storageBucket: 'gesturo-a6e9c.firebasestorage.app',
    iosBundleId: 'com.example.gesturo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQDQCPrnwYparXNln0qLz1tDMdQtUbe1g',
    appId: '1:322888842794:web:407b6cee4f44df1d80cd53',
    messagingSenderId: '322888842794',
    projectId: 'gesturo-a6e9c',
    authDomain: 'gesturo-a6e9c.firebaseapp.com',
    storageBucket: 'gesturo-a6e9c.firebasestorage.app',
    measurementId: 'G-2P0R55J7NQ',
  );
}
